# Generated by Django 5.1.7 on 2025-03-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(default='abidjan', max_length=220)),
                ('titre', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('pdf_recapitulatif', models.FileField(blank=True, null=True, upload_to='doc_pdf/')),
                ('img_formation', models.ImageField(blank=True, default='doc_img_formation/img.png', null=True, upload_to='doc_img_formation/')),
                ('save_date', models.DateTimeField(auto_now_add=True)),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-save_date'],
            },
        ),
        migrations.CreateModel(
            name='ImageRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='doc_img/')),
                ('description', models.ImageField(upload_to='')),
                ('save_date', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_BelAvenir.rapportformation')),
            ],
            options={
                'ordering': ['-save_date'],
            },
        ),
        migrations.CreateModel(
            name='VideosRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='doc_video/')),
                ('description', models.TextField()),
                ('save_date', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_BelAvenir.rapportformation')),
            ],
            options={
                'ordering': ['-save_date'],
            },
        ),
    ]
